# Generated by Django 3.2.4 on 2022-05-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapi', '0006_auto_20220520_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='message',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
